version: '3.9'

services:
  ui:
    container_name: 'myapp'
    image: 'myapp'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - "keycloak"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:17.0.1
    environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev

