on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - uses: 'docker'
      - image: 'Dockerfile'
